kind: MLApp
metadata:
  name: gan-image-similarity
spec:
  package_manager: "pip{{.python_version}}"
  packages:
    - names:
      {{- range $i, $value := .packages }}
      - "{{ $value }}"
      {{- end }}
      manager: "pip{{.python_version}}"
  tasks:
  - name: prepare-data
    resources:
    - name: upload
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 1
      allowFail: true
      images:
        cpu: busybox
      command: "echo \"Uploading Data\";echo \"Done!!!\""
      workdir: "$DATA_DIR"
      volumes:
      - name: data
  - name: standalone
    resources:
    - name: worker
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      allowFail: true
      {{- if eq .python_version "3" }}
      images:
        gpu: "tensorflow/tensorflow:{{.tensorflow_version}}-gpu-py3"
        cpu: "tensorflow/tensorflow:{{.tensorflow_version}}-py3"
      {{- end }}
      {{- if eq .python_version "2" }}
      images:
        gpu: "tensorflow/tensorflow:{{.tensorflow_version}}-gpu"
        cpu: "tensorflow/tensorflow:{{.tensorflow_version}}"
      {{- end }}
      command: python
      args: hello.py
      workdir: "$SRC_DIR"
      resources:
        accelerators:
          gpu: 0
          dedicated_gpu: true
        requests:
          cpu: 100m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 8Gi
      volumes:
      - name: lib
      - name: training
      - name: src
      - name: data
      - name: code
  - name: parallel
    resources:
    - name: worker
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      allowFail: true
      {{- if eq .python_version "3"}}
      images:
        gpu: "tensorflow/tensorflow:{{.tensorflow_version}}-gpu-py3"
        cpu: "tensorflow/tensorflow:{{.tensorflow_version}}-py3"
      {{- end }}
      {{- if eq .python_version "2"}}
      images:
        gpu: "tensorflow/tensorflow:{{.tensorflow_version}}-gpu"
        cpu: "tensorflow/tensorflow:{{.tensorflow_version}}"
      {{- end }}
      command: "echo \"WORKER: $REPLICA_INDEX\";echo \"PSS: $PS_NODES\"; echo \"WORKERS: $WORKER_NODES\"; echo \"BUILD: $BUILD_ID\"; python"
      args: hello.py
      workdir: "$SRC_DIR"
      resources:
        accelerators:
          gpu: 0
          dedicated_gpu: true
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 4Gi
      port: 2222
      volumes:
      - name: lib
      - name: training
      - name: src
      - name: data
      - name: code
    - name: ps
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      {{- if eq .python_version "3"}}
      images:
        gpu: "tensorflow/tensorflow:{{.tensorflow_version}}-gpu-py3"
        cpu: "tensorflow/tensorflow:{{.tensorflow_version}}-py3"
      {{- end }}
      {{- if eq .python_version "2"}}
      images:
        gpu: "tensorflow/tensorflow:{{.tensorflow_version}}-gpu"
        cpu: "tensorflow/tensorflow:{{.tensorflow_version}}"
      {{- end }}
      command: "echo \"PS: $REPLICA_INDEX\";echo \"PSS: $PS_NODES\"; echo \"WORKERS: $WORKER_NODES\"; echo \"BUILD: $BUILD_ID\"; python"
      args: hello.py
      workdir: "$SRC_DIR"
      port: 2222
      volumes:
      - name: src
      - name: code
  - name: export
    resources:
    - name: worker
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      allowFail: true
      {{- if eq .python_version "3"}}
      images:
        gpu: "tensorflow/tensorflow:{{.tensorflow_version}}-gpu-py3"
        cpu: "tensorflow/tensorflow:{{.tensorflow_version}}-py3"
      {{- end }}
      {{- if eq .python_version "2"}}
      images:
        gpu: "tensorflow/tensorflow:{{.tensorflow_version}}-gpu"
        cpu: "tensorflow/tensorflow:{{.tensorflow_version}}"
      {{- end }}
      command: "echo \"BUILD: $BUILD_ID\"; python"
      args: hello.py
      workdir: "$SRC_DIR"
      resources:
        accelerators:
          gpu: 0
          dedicated_gpu: true
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 4Gi
      volumes:
      - name: lib
      - name: training
      - name: src
      - name: data
      - name: code
  - name: workflow
    resources:
    - name: tasks
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      allowFail: false
      {{- if eq .python_version "3" }}
      images:
        gpu: "tensorflow/tensorflow:{{.tensorflow_version}}-gpu-py3"
        cpu: "tensorflow/tensorflow:{{.tensorflow_version}}-py3"
      {{- end }}
      {{- if eq .python_version "2" }}
      images:
        gpu: "tensorflow/tensorflow:{{.tensorflow_version}}-gpu"
        cpu: "tensorflow/tensorflow:{{.tensorflow_version}}"
      {{- end }}
      command: python
      args: run_tasks.py
      workdir: "$SRC_DIR"
      resources:
        accelerators:
          gpu: 0
          dedicated_gpu: true
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 1Gi
      volumes:
      - name: lib
      - name: training
      - name: src
      - name: data
      - name: code
  uix:
  - name: jupyter
    displayName: Jupyter
    {{- if eq .python_version "3"}}
    images:
      gpu: "kuberlab/mlboard-jupyter-gpu:latest-py3"
      cpu: "kuberlab/mlboard-jupyter:latest-py3"
    {{- end }}
    {{- if eq .python_version "2"}}
    images:
      gpu: "kuberlab/mlboard-jupyter-gpu:latest"
      cpu: "kuberlab/mlboard-jupyter:latest"
    {{- end }}
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 4Gi
    ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
    volumes:
    - name: lib
      mountPath: /notebooks/lib
    - name: src
      mountPath: /notebooks/src
    - name: training
      mountPath: /notebooks/training
    - name: data
      mountPath: /notebooks/data
    - name: code
      mountPath: /notebooks
  - name: tensorboard
    displayName: Tensorboard
    command: "tensorboard"
    args: "--logdir=$TRAINING_DIR"
    images:
      cpu: "lsheiba/tensorflow-ls-devel"
    ports:
    - port: 6006
      targetPort: 6006
      protocol: TCP
      name: http
    volumes:
    - name: training
  serving:
  - name: serving
    displayName: Serving
    {{- if .tf_serving }}
    images:
      gpu: "kuberlab/tensorflow-serving:latest-gpu"
      cpu: "kuberlab/tensorflow-serving:latest"
    command: tensorflow_model_server
    args: "--port={{ .serving_port }} --model_name=$TASK_NAME --model_base_path=$TRAINING_DIR/$BUILD_ID"
    {{- else }}
    {{- if eq .python_version "3"}}
    images:
      gpu: "tensorflow/tensorflow:{{.tensorflow_version}}-gpu-py3"
      cpu: "tensorflow/tensorflow:{{.tensorflow_version}}-py3"
    {{- end }}
    {{- if eq .python_version "2"}}
    images:
      gpu: "tensorflow/tensorflow:{{.tensorflow_version}}-gpu"
      cpu: "tensorflow/tensorflow:{{.tensorflow_version}}"
    {{- end }}
    workdir: "$SRC_DIR"
    command: python
    args: hello.py
    {{- end }}
    resources:
      accelerators:
        gpu: 0
        dedicated_gpu: true
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 1000m
        memory: 4Gi
    ports:
    - port: {{ .serving_port }}
      targetPort: {{ .serving_port }}
      protocol: TCP
      name: http
    volumes:
    - name: training
    - name: data
    - name: src
    - name: lib
    - name: code
  volumes:
  - isLibDir: false
    isTrainLogDir: true
    mountPath: /training
    name: training
    clusterStorage: {{ .storage }}
    subPath: training
  - gitRepo:
      repository: {{ .src }}
    isLibDir: false
    isTrainLogDir: false
    mountPath: /src
    name: src
    subPath: "{{ .src_path }}"
  - isLibDir: true
    isTrainLogDir: false
    mountPath: /workspace/lib
    name: lib
    clusterStorage: {{ .storage }}
    subPath: lib
  - isLibDir: false
    isTrainLogDir: false
    mountPath: /data
    name: data
    clusterStorage: {{ .storage }}
    subPath: {{ .data_path }}
  - isLibDir: false
    isTrainLogDir: false
    mountPath: /code
    name: code
    subPath: code
    clusterStorage: {{ .storage }}
